-- Marwadi Samaj Indore app — complete database setup, in one paste.
-- GENERATED by scripts/combine-sql.mjs from: schema.sql, 002-biodata.sql, 003-meetings.sql, 004-meeting-rsvps-and-committee.sql, 005-meeting-organisers.sql, 006-meeting-maps-link.sql, 007-meeting-drive-link.sql, 008-circulars.sql.
-- Do not edit this file; edit the numbered files and run `npm run sql`.
-- Safe to run more than once.

-- =============================================================================
-- >>> schema.sql
-- =============================================================================

-- =============================================================================
-- Marwadi Samaj Indore app — database schema
--
-- Paste this whole file into the Supabase SQL Editor and press Run.
-- Safe to run more than once.
--
-- SECURITY MODEL
-- Members never talk to this database directly. Every read and write goes
-- through the app's own server code, which checks permissions first (see
-- lib/session.ts canEdit). So Row Level Security is switched ON with no public
-- policies at all: the anon key can read nothing, and the server connects with
-- the service key which bypasses RLS. That means a leaked anon key exposes
-- nothing, and there are no subtle policy holes to get wrong.
--
-- GRANTS — the second lock, and the one PMConnect never needed to write
-- This project is created with "Automatically expose new tables" switched
-- OFF (Supabase's default for projects created from 30 May 2026). With it off,
-- a new table is granted to none of the API roles: not anon, not
-- authenticated, and not service_role — the role this app's server uses for
-- everything. So access is granted here, explicitly, to service_role alone.
-- The anon key then has no privileges on any table at all, on top of RLS
-- refusing it, which is two locks where PMConnect had one.
-- =============================================================================

-- Every table created from here on by the SQL Editor (which runs as postgres),
-- including all the numbered files that follow this one, is granted to the
-- server's role the moment it exists. Nothing is granted to anon or
-- authenticated.
alter default privileges for role postgres in schema public
  grant select, insert, update, delete on tables to service_role;
grant usage on schema public to service_role;

-- ----------------------------------------------------------------- households
create table if not exists households (
  id            text primary key,
  family_name   text not null,
  surname       text default '',
  gotra         text default '',
  native_place  text default '',
  address       text default '',
  area          text default '',
  city          text default 'Indore',
  pincode       text default '',
  maps_url      text default '',
  photo         text,
  anniversary   date,
  head_person_id text,
  source_row    integer,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists households_area_idx on households (area);
create index if not exists households_surname_idx on households (surname);
-- Day-and-month lookup for "today's anniversaries", ignoring the year
create index if not exists households_anniversary_md_idx
  on households (extract(month from anniversary), extract(day from anniversary));

-- --------------------------------------------------------------------- people
create table if not exists people (
  id               text primary key,
  household_id     text not null references households (id) on delete cascade,
  first_name       text not null default '',
  middle_name      text default '',
  last_name        text default '',
  relationship     text not null default 'other'
                     check (relationship in ('self','spouse','child','parent','other')),
  gender           text default '',
  photo            text,
  mobile           text,
  whatsapp         text,
  email            text default '',
  dob              date,
  blood_group      text default '',
  marital_status   text default '',
  living_in        text default '',
  education        text default '',
  occupation_type  text default '',
  business         jsonb not null default '{}'::jsonb,
  privacy          jsonb not null default '{}'::jsonb,
  deceased         boolean not null default false,
  claimed_by_email text,
  age              integer,
  birth_year       integer,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create index if not exists people_household_idx on people (household_id);
create index if not exists people_mobile_idx on people (mobile);
create index if not exists people_claimed_idx on people (claimed_by_email);
create index if not exists people_category_idx on people ((business ->> 'category'));
create index if not exists people_dob_md_idx
  on people (extract(month from dob), extract(day from dob));

-- The identity gate looks members up by the last 4 digits of their mobile
create index if not exists people_mobile_last4_idx on people (right(mobile, 4));

-- ---------------------------------------------------------------------- posts
-- Announcements and requirements share one table, separated by `type`
create table if not exists posts (
  id               text primary key,
  type             text not null check (type in ('announcement','requirement')),
  author_person_id text references people (id) on delete set null,
  author_name      text not null default '',
  author_email     text,
  title            text not null,
  body             text not null default '',
  category         text default '',
  area             text default '',
  photo            text,
  pinned           boolean not null default false,
  comments_locked  boolean not null default false,
  is_demo          boolean not null default false,
  created_at       timestamptz not null default now(),
  expires_at       timestamptz
);

create index if not exists posts_type_created_idx on posts (type, created_at desc);
create index if not exists posts_expires_idx on posts (expires_at);

-- ------------------------------------------------------------------- comments
create table if not exists comments (
  id               text primary key,
  post_id          text not null references posts (id) on delete cascade,
  author_person_id text references people (id) on delete set null,
  author_name      text not null default '',
  author_email     text,
  body             text not null,
  created_at       timestamptz not null default now()
);

create index if not exists comments_post_idx on comments (post_id, created_at);

-- --------------------------------------------------------------------- issues
-- The admin "needs attention" queue produced by the Excel import
create table if not exists issues (
  id           text primary key,
  household_id text references households (id) on delete cascade,
  person_id    text references people (id) on delete cascade,
  field        text not null default '',
  kind         text not null default '',
  message      text not null default '',
  raw          text default '',
  resolved     boolean not null default false
);

create index if not exists issues_open_idx on issues (resolved, kind);

-- ----------------------------------------------------------------- change log
-- Powers the admin recent-changes feed and one-click undo
create table if not exists change_log (
  id       text primary key,
  at       timestamptz not null default now(),
  by_email text,
  by_name  text default '',
  action   text not null default '',
  target   text default '',
  before   jsonb,
  after    jsonb,
  undone   boolean not null default false
);

create index if not exists change_log_at_idx on change_log (at desc);

-- --------------------------------------------------------------------- admins
-- Committee members, matched on the email from their Google sign-in
create table if not exists admins (
  email      text primary key,
  added_at   timestamptz not null default now()
);

insert into admins (email) values
  ('anandjain0498@gmail.com'),
  ('marwadisamajindore@gmail.com')
  on conflict (email) do nothing;

-- ------------------------------------------------------------- keep timestamps
create or replace function touch_updated_at() returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists households_touch on households;
create trigger households_touch before update on households
  for each row execute function touch_updated_at();

drop trigger if exists people_touch on people;
create trigger people_touch before update on people
  for each row execute function touch_updated_at();

-- ------------------------------------------------------ lock everything down
-- RLS on, no policies: nothing is readable or writable with the public anon
-- key. The app's server connects with the service key and bypasses RLS after
-- doing its own permission checks.
alter table households enable row level security;
alter table people     enable row level security;
alter table posts      enable row level security;
alter table comments   enable row level security;
alter table issues     enable row level security;
alter table change_log enable row level security;
alter table admins     enable row level security;

-- Belt and braces for the tables above, in case this file is ever run on a
-- project whose default privileges were set differently.
grant select, insert, update, delete on all tables in schema public to service_role;

-- ------------------------------------------------------------- photo storage
-- Member photos live in a private bucket, not in the database
insert into storage.buckets (id, name, public)
values ('member-photos', 'member-photos', false)
on conflict (id) do nothing;

-- =============================================================================
-- >>> 002-biodata.sql
-- =============================================================================

-- =============================================================================
-- Migration 002 — marriage biodata repository
--
-- Paste into the Supabase SQL Editor and press Run. Safe to run twice.
--
-- A biodata is NOT tied to a member record. Members share documents for
-- relatives who may live anywhere and may not be in the samaj at all, so the
-- subject is just a name typed by the uploader. One member can share many.
--
-- The point of contact is whoever uploaded it — that is the person another
-- family should message.
-- =============================================================================

-- PMConnect's copy of this file began by dropping the table, to replace an early
-- draft keyed on person_id. This app never had that draft, and a drop here would
-- wipe every shared biodata if the file were ever run again, so it creates the
-- table only when missing, like every other file.
create table if not exists biodata (
  id            text primary key,
  title         text not null,          -- name of the person the biodata is for
  file_path     text not null,
  file_type     text not null default 'pdf' check (file_type in ('pdf', 'image')),
  file_name     text default '',
  note          text default '',
  -- Who shared it, and therefore who to contact
  uploader_person_id text references people (id) on delete set null,
  uploader_name text default '',
  uploader_email text,
  created_at    timestamptz not null default now()
);

create index if not exists biodata_created_idx on biodata (created_at desc);
create index if not exists biodata_uploader_idx on biodata (uploader_person_id);

-- Same posture as every other table: no public access. Members reach this only
-- through the app's own server code, which checks permissions first.
alter table biodata enable row level security;

-- =============================================================================
-- >>> 003-meetings.sql
-- =============================================================================

-- =============================================================================
-- Migration 003 — group meetings
--
-- Paste into the Supabase SQL Editor and press Run. Safe to run twice.
--
-- Committee-posted, like an announcement — outings, monthly get-togethers,
-- themed evenings. The Kwik Pic link is added afterwards, once photos from
-- the meeting are ready to share. Deliberately small: no comments, no RSVP.
-- =============================================================================

create table if not exists meetings (
  id            text primary key,
  title         text not null,
  description   text default '',
  location      text default '',
  meeting_date  date not null,
  meeting_time  text default '',
  photo         text,
  kwik_pic_url  text,
  author_name   text default '',
  author_email  text,
  created_at    timestamptz not null default now()
);

create index if not exists meetings_date_idx on meetings (meeting_date desc);

-- Same posture as every other table: no public access. Members reach this only
-- through the app's own server code, which checks permissions first.
alter table meetings enable row level security;

-- =============================================================================
-- >>> 004-meeting-rsvps-and-committee.sql
-- =============================================================================

-- =============================================================================
-- Migration 004 — meeting attendance (RSVP) and the committee section
--
-- Paste into the Supabase SQL Editor and press Run. Safe to run twice.
-- =============================================================================

-- One row per (meeting, person) — a member's headcount for that meeting,
-- e.g. "3 of us are coming". Upserted if they change their mind.
create table if not exists meeting_rsvps (
  id             text primary key,
  meeting_id     text not null references meetings (id) on delete cascade,
  person_id      text not null references people (id) on delete cascade,
  household_id   text not null references households (id) on delete cascade,
  attendee_count integer not null default 1 check (attendee_count between 1 and 20),
  responder_name text default '',
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  unique (meeting_id, person_id)
);

create index if not exists meeting_rsvps_meeting_idx on meeting_rsvps (meeting_id);
alter table meeting_rsvps enable row level security;

-- The committee section on Home — president, patrons, secretaries. Small and
-- admin-managed, not linked to a household. sort_order 0 is shown biggest.
create table if not exists committee_members (
  id         text primary key,
  name       text not null,
  role       text not null default '',
  phone      text,
  photo      text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists committee_members_order_idx on committee_members (sort_order);
alter table committee_members enable row level security;

-- =============================================================================
-- >>> 005-meeting-organisers.sql
-- =============================================================================

-- =============================================================================
-- Migration 005 — meeting organisers
--
-- Paste into the Supabase SQL Editor and press Run. Safe to run twice.
--
-- Free text, not a link to people — the organiser is often named the way the
-- committee would say it out loud ("Suresh & Rekha Jain"), not necessarily a
-- member already in the directory.
-- =============================================================================

alter table meetings add column if not exists organisers text default '';

-- =============================================================================
-- >>> 006-meeting-maps-link.sql
-- =============================================================================

-- =============================================================================
-- Migration 006 — meeting Google Maps link
--
-- Paste into the Supabase SQL Editor and press Run. Safe to run twice.
--
-- Same idea as household.maps_url — "Location" stays a plain venue name
-- (e.g. "Geeta Bhawan community hall"), this is the optional link that
-- actually opens the pin.
-- =============================================================================

alter table meetings add column if not exists maps_url text;

-- =============================================================================
-- >>> 007-meeting-drive-link.sql
-- =============================================================================

-- =============================================================================
-- Migration 007 — meeting Google Drive link
--
-- Paste into the Supabase SQL Editor and press Run. Safe to run twice.
--
-- Sits beside kwik_pic_url rather than replacing it. Kwik Pic is where the
-- photographer's set goes; a Drive folder is where everything else does —
-- the papers, the video, the shots members took themselves.
-- =============================================================================

alter table meetings add column if not exists drive_url text;

-- =============================================================================
-- >>> 008-circulars.sql
-- =============================================================================

-- =============================================================================
-- Migration 008 — committee circulars
--
-- Paste into the Supabase SQL Editor and press Run. Safe to run twice.
--
-- A circular is a document, not a post. It is typed on letterhead, signed, and
-- referred back to months later, so the file is the thing and the title and
-- note exist only to make it findable without opening it.
--
-- Deliberately its own table rather than a third `posts.type`. Posts carry
-- comments, pinning, expiry and a weekly limit per member, none of which a
-- circular wants; the shared column would have been mostly nulls in both
-- directions.
-- =============================================================================

create table if not exists circulars (
  id            text primary key,
  title         text not null,
  note          text default '',
  file_path     text not null,
  file_type     text not null default 'pdf' check (file_type in ('pdf', 'image')),
  file_name     text default '',
  -- Who posted it. Only the committee can, but which member of it matters
  author_person_id text references people (id) on delete set null,
  author_name   text default '',
  author_email  text,
  created_at    timestamptz not null default now()
);

create index if not exists circulars_created_idx on circulars (created_at desc);

-- Same posture as every other table: no public access. Members reach this only
-- through the app's own server code, which checks permissions first.
alter table circulars enable row level security;
