// Joins schema.sql and the numbered migrations into supabase/setup-all.sql, so a
// brand-new Supabase project is set up with ONE paste into the SQL Editor
// instead of eight. The numbered files stay the source of truth — never edit
// setup-all.sql by hand; run `npm run sql` after changing any of them.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";

const dir = new URL("../supabase/", import.meta.url);
const numbered = readdirSync(dir)
  .filter((f) => /^\d{3}-.*\.sql$/.test(f))
  .sort();
const files = ["schema.sql", ...numbered];

const parts = files.map(
  (f) =>
    `-- =============================================================================\n` +
    `-- >>> ${f}\n` +
    `-- =============================================================================\n\n` +
    readFileSync(new URL(f, dir), "utf8").trimEnd() +
    "\n"
);

const header =
  `-- Marwadi Samaj Indore app — complete database setup, in one paste.\n` +
  `-- GENERATED by scripts/combine-sql.mjs from: ${files.join(", ")}.\n` +
  `-- Do not edit this file; edit the numbered files and run \`npm run sql\`.\n` +
  `-- Safe to run more than once.\n\n`;

writeFileSync(new URL("setup-all.sql", dir), header + parts.join("\n"));
console.log(`supabase/setup-all.sql written from ${files.length} files: ${files.join(", ")}`);
